---
title: 'Keeping Space for Jobs: Evaluating Industrial Land Protection Policies'
author: "Jamaal Green"
date: "3/13/2018"
output: 
  pdf_document:
    number_sections: TRUE
bibliography: tmp-clean-file.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

#Introduction

The story of US deindustrialization is well known. From the decentralization of industrial plants from union heavy northern areas to the offshoring of production to Asia, the general narrative of US manufacturing employment is one of traumatic decline that devastates communities and is responsible for growing income inequality [@BluestonedeindustrializationAmericaPlant1982].These losses are often attributed to growing productivity, skill biased technical change or labor copetition from lower cost countries [@WeaverSkillDemandsMismatch2016]. But this narrative may overstate possible effects missing alternative explanations such as the role of changing corporate strategy and structure on management decision [@BergerHowFinanceGutted2014]. Urban planners, geographers, and regional economic development shcolars are now highlightling another potential major factor in local deindustrialization-- local and regional land use management, specifically, the loss of land available for industry.

Recent research has tracked the dramatic loss of industrially zoned land in growing, large US cities. Recent analyses from Leigh and Hoelzel [-@LeighSmartGrowthBlind2012], Chappel[-@ChappleHighestBestUse2014], and Lester et al [@LesterMakingRoomManufacturing2013] have explored how dominant urban policy approaches are oriented towards the conversion of industrial lands to non-industrial uses accelerating local labor market restructuring and deindustrialization. Recognizing these gaps, a select number of large US cities have passed new regulations protecting industrial and employment lands. Though cities, and researchers, argue that preserving industrial land will help keep manufacturing and industrial jobs in cities, there is a lack of research on the actual jobs impact of such policies. This is due to a combination of the novelty of these policies (many were passed in the last fifteen years) and the lack of available employment data at fine enough geographies to reasonably estimate employment impact at the intra-city scale. 

This study relies on a novel dataset of existing industrial preservation policies within the US's fifty largest cities and local employment data from the Census's Longitudinal Employment Household Dynamics (LEHD) Origin-Destination Employment statistics dataset.The LEHD allows for the estimation of the effect of industrial land preservation policies on protecting industrial jobs pre and post-Great Recession.

The next section of the study will review the existing literature on industrial land preservation and labor market restructuring, followed by a description of the study's methodology and data, and final discussion section. 

#Literature Review

This section will cover recent work on land-use change and labor market restructuring. First, the predominant land-use policy paradigm in the contemporary us- Smart Growth- is under increased scrutiny for encouraging cities to converty industrial land to non-industrial uses regardless of its current strategic or employment value highlighting a growing contradiction in many cities across the US as they attempt to balance robust population growth with maintaining existing industrial jobs. Second, the question of industrial land, land-use change, local labor market restructuring, and business growth has come back to the fore for economic development researchers. Succinctly, what are the actual labor market and business effects of converting industrial land? Finally, conversion is    

##Blindness and Best Uses

The predominant land-use policy paradigm in the US today is Smart Growth. While, not all major cities necessarily call their plans Smart Growth plans, the general principles of encouraging mixed-use, transit-oriented development and densifying existing urban areas are now common place and owe their popularity largely to the spread of Smart Growth principles. Unfortunately, Smart Growth proponents have generally ignored the value of industrial lands. Leigh and Hoelzel [-@LeighSmartGrowthBlind2012] reviewed the industrial policies of 13 cities and 10 major Smart Growth publications from Smart Growth America, the Environmental Protection Agency, and PAS guides from the American Planning Association. They found that while cities may be concerned with the loss of industrial land and jobs, the dominant land-use guides cities draw generally frame industrial land in a negative light as either obsolete, a fiscal drag, or generally polluted. Leigh and Hoelzel highlight a major contradiction in many cities, especially faster growing cities, where policymakers are aware of the importance industrial land and jobs, and even have policies to support them, yet their land-use policies work directly against them by encouraging the conversion of industrial land to non-industrial uses.

A common reason for the conversion of industrial land to non-industrial uses is that land should be given over to its "highest and best use". Thus an industrial district in a growing part of a city should be converted to non-industrial if developers are willing to outbid existing industrial users for the land. This argument is generally supported on efficiency grounds but it utterly devalues the role that industrial land, and users play, in greater urban and regional economic development and business growth. Chapple [-@ChappleHighestBestUse2014] offers one challenge to this assertion by estimating the role of industrially zoned land in regional business dynamics- the creation, growth, and death of firms. Chapple finds that firm creation, and growth of newer firms, are correlated with the availability of industrially zoned land in four Bay Area cities. The theory underlying these results is that available industrial land not only lowers start up costs for new firms, but also allows firms to expand *in place*. Industrial land will not make ineffective firms viable but industrial land does make already effective firms stronger by offering them flexible space to expand into.

While Chapple (2014) examined the regional business dynamics of industrial land supply, Lester and Hartley [-@Lesterlongtermemployment2014] estimate the effect of local neighborhood gentrification on labor markets. They find that local gentrification has moderate positive overall effects on employment growth but it also responsible for dramatic industrial restructuring in neighborhoods replacing prior industrial jobs with lesser paid service jobs. In their findings, Lester and Hartley link the processes of social, and physical, neighborhood change to localized economic restructuring. Lester and Hartley's work should be seen as an extension of Curran's [-@CurranGentrificationnaturework2004; -@CurranFryingPanOven2007] work examining the local policies and practices that forcibly displace manufacturing firms as part of broader, global patterns in capital accumulation and uneven development. Both sets of studies, though, are unequivocal in stating that industrial employment change, particularly deindustrialization, is not wholly an exogneous phenomenon but one that is intimately tied to *local* policies and priorities. Curran, in particular, examines the interplay of deindustrialization, labor disputes, and city real-estate interests combine to weaken the standing of industrial employers in Brooklyn as well as contribute to an overall narrative of industrial decline. 

##Placing Urban Manufacturing

The industrial location literature is voluminous, arguably forming the foundation of much of urban economics, economic geography, and urban studies/planning theory and history. McCann et al [-@MccannRiseFallRise2003] give a thorough review of industrial location theory tracing the history of the production-optimization problems that undergird classical industrial location theory, a la Weber and Von Thunen, to the spatial transaction costs models of neoclassical theorists such as Alonso and, later, Glaeser. production optimization problem, meaning that as
long as firm factor substitutions are properly specified then the location choice of firms is solvable. In other words, firms will locate in areas that allow them to find an equilibrium position between a firm’s production function and its external spatial transaction costs (in this case, commonly assumed to be transportation costs). Glaeser et al [-@GlaeserCitiesregionsdecline2003] offer support for these assumptions by noting the decentralization of manufacturing firms and workers in the face of decreasing transportation costs throughout the 20th century US.

But while neoclassical industrial location offers reasoning for the continued decentralization of US manufacturing we see that urban manufacturing persists in many places. Byron and Mistry's [-@ByronFederalRoleSupporting2011] Brookings report on urban manufacturing highlights the metropolitan centralization of smaller urban manufacturing firms that benefits from a variety of benefits in urban areas including, but not limited to, proximity to customers and suppliers and the ability to draw on the larger skilled labor markets in metropolitan areas.These smaller firms, more dependent upon existing relations with proximal firms and close working relationships with clients, garner their competitive advantages precisely *because* they are urban. Van Winden at al [-@VanWindenManufacturingnewurban2010] expand on this point in their 2010 volume on urban manufacturing in Europe noting that more advanced manufacturing requiring closer relationships with clients for prototyping and testing reward proximity and encourage agglomeration. In short, aspects of contemporary manufacturing and industrial work have distinct urban biases. The massive single story production facilities for automobiles may never return to American cities, but they do not have to in the face of other manufacturing industries in food processing, semiconductors or autonomous vehicle prototyping and testing. 

*Potentially add something on stick places or working regions here* 


Chapple, Curran, and Lester et al examine different angles of the question of local land-use change and labor market restructuring, but they also speak to a broader conflict in economic development policy- industrial retention versus new firm growth. In actuality, these are less opposite poles than overlapping areas of policy concern and cities often claim they are doing both. 

#Data and Methodology

##Data

The primary data source for this study is the Workplace Area Characteristic (WAC)  file Longitudinal Origin-Destination Employment Series (LODES) dataset from the Longitudinal Household Employment Dynamics (LEHD) dataset from the US Census Bureau[^1]. The LODES dataset combines administrative employment data from state unemployment insurance filings with Census population information to offer a geographically fine (census block level) measure of employment for major industrial categories. In addition to its geographic specificity, most states in the country have LODES data going back to 2002 allowing for a truly longitudinal study of the changes in the geography of jobs. 

For this study, I collected LODES WAC data for the years 2004, 2005, and 2009 for 47 of the US's 50 largest cities aggregated to the block group level. LODES data is prepared alreayd normalized to 2010 census geographies allowing for valid comparisons across time and the ability to easily join the data to other census sources. From the three years of data I collected LODES estimates of total, agricultural, mining, utilities, manufacturing, wholesale trade, and transportation employment for all primary jobs (LEHD job type code "JT01").

Block group population data was collected from the 2005-2009 American Community Survey from NHGIS [@StevenMansonIPUMSNationalHistorical2017]. The ACS information collected included estimates of total, Non-Hispanic White, Non-Hispanic Black, and Hispanic residents. Additionally, I collected the total number of housing units and the total number of owner and renter occupied units. Finally, I calculated total population density (km^2).

Street network density data was collected from the Environmental Protection Agenciy's Smart Location Database (SLD) [@EnvironmentalProtectionAgencyEPASmartLocation2013]. The SLD is the most comprehensive national level database of the urban built environment publicly available collected at the block group level. 

Finally, I include dummy variables for whether a block group intersects with what I call a PMD (named after Chicago's Plannined Manufacturing Districts) policy. 

[^1]: Further technical details on the LODES dataset can be found here: [https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.3.pdf](https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.3.pdf)



#References